const char* AP_SSID = "<WLAN-ESSID>";
const char* AP_PASSWORD = "<WLAN-PASSWORD>";
const char* HIPCHAT_CHANNEL = "<HIPCHAT CHANNEL ID";
const char* HIPCHAT_TOKEN = "<SECURITY TOKEN>";
const char* HIPCHAT_THUMBPRINT = "<SERVER THUMBPRINT>";
